language: haskell
dist: xenial

cache:
  directories:
  - "$HOME/.cabal"

ghc:
- 8.6.5
- 8.4.4
- 8.2.2
- 8.0.2
- 7.10.3
- 7.8.4
- 7.6.3

install:
- cabal configure && cabal build && cabal haddock

script:
- echo "no tests"
